### ISSUE TITLE
Wont start on Kali rolling 2016.1

### ISSUE THREAD

**Issue by joeisgood99** [infobyte/evilgrade#10]
Same or similar issue as issue #5 which was closed with a fix.
Im getting this issue on Kali rolling 2016.1. with fresh git clone of evilgrade as of 25/06/2016.
Have installed RPC::XML and Data::Dump with apt-get install librpc-xml-perl && apt-get install libdata-dump-perl.

Error:
```
www.infobytesec.com

    78 modules available.

evilgrade>Use of uninitialized value $prompt in concatenation (.) or string at /usr/lib/x86_64-linux-gnu/perl5/5.22/Term/ReadLine/Gnu.pm line 318
```
Regards.

**Comment by franc205** [comment]
Hi, I solve it on Ubuntu doing an apt-get remove --purge libterm-readline-gnu-perl. Apparently this lib generate an internal problem in evilgrade.

**Comment by mattaereal** [comment]
Hi there. This error has been fixed on the latest releases. Just update.

You can also just do a git clone or pull from our latest version.



On Wed, Jul 6, 2016 at 8:30 PM, franc205 <notifications@github.com> wrote:

> Hi, I solve it on Ubuntu doing an apt-get remove --purge
> libterm-readline-gnu-perl. Apparently this lib generate an internal problem
> in evilgrade.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/infobyte/evilgrade/issues/10#issuecomment-230938101>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXt_eXGnHvgiz7qEYKTXQz7seKDhkmeks5qTDqqgaJpZM4I-q1k>
> .
>



-- 
Atte:
Matías Aereal Aeón

**Comment by mattaereal** [comment]
My apologies, I misread your description. This is weird. Can you tell me
exactly where this is happening?

The bug is in the library but we handled it in our source code. ReadLine
assumes that there's always content on a new line. But when you were on the
cli and pressed enter, the unitialized warning appeared. It was handled by
adding a space character in case of empty string when pressing enter.

**Comment by joeisgood99** [comment]
No probs!
Happens on start up just after you run ./evilgrade.
I cd to evilgrade dir, run ./evilgrade. All modules load and the logo comes up followed by the error. see below.

> [DEBUG] - Loading module: modules/osx.pm
> [DEBUG] - Loading module: modules/autoit3.pm
>             _ _                     _      
>            (_) |                   | |     
>   _____   ___| | __ _ _ __ __ _  __| | ___ 
>  / _ \ \ / / | |/ _` | '__/ _` |/ _` |/ _ \ 
> |  __/\ V /| | | (_| | | | (_| | (_| |  __/ 
>  \___| \_/ |_|_|\__, |_|  \__,_|\__,_|\___| 
>                 __/ |                      
>                 |___/ 
> -------------------------------------------
> ---------------------  www.infobytesec.com 
> - 78 modules available.
> 
> evilgrade>Use of uninitialized value $prompt in concatenation (.) or string at /usr/lib/x86_64-linux-gnu/perl5/5.22/Term/ReadLine/Gnu.pm line 318.

Purging libterm-readline-gnu-perl works as a temp fix. 

Odd that the same error happens a few lines down from where you fixed it last. ...Let me know if I can do anything to help.

**Comment by mattaereal** [comment]
I will have to check this again. Maybe ReadLine was updated on some way
that is preventing the fix I added on evilgrade to work.

I'll work it out soon enough. But don't you worry, it's just a warning, it
does not affect evilgrade's functionality. It's just annoying.

Thanks again for your feedback!

On Thu, Jul 7, 2016 at 10:37 AM, joeisgood99 <notifications@github.com>
wrote:

> No probs!
> Happens on start up just after you run ./evilgrade.
> I cd to evilgrade dir, run ./evilgrade. All modules load and the logo
> comes up followed by the error. see below.
>
> [DEBUG] - Loading module: modules/osx.pm
> [DEBUG] - Loading module: modules/autoit3.pm
> _ _ _
>
> (
>
> *) | | | ____*
> *| | _ _ _ __ __ _ __| | ___ / _ \ \ / / | |/ _` | '*/
> *|/ _ |/ _ \ | _*/\ V /| | | (*| | | | (*| | (*| | _*/
> ___| _/ |*|*|__, |*| _*,*|_*,*|__*|
> __/ |
> |___/
>
> --------------------- www.infobytesec.com
>
>    - 78 modules available.
>
> evilgrade>Use of uninitialized value $prompt in concatenation (.) or
> string at /usr/lib/x86_64-linux-gnu/perl5/5.22/Term/ReadLine/Gnu.pm line
> 318.
>
> Purging libterm-readline-gnu-perl works as a temp fix.
>
> Odd that the same error happens a few lines down from where you fixed it
> last. ...Let me know if I can do anything to help.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/infobyte/evilgrade/issues/10#issuecomment-231079527>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXt_Y17Q8Aw-eDD03Gno0810naptTrVks5qTQENgaJpZM4I-q1k>
> .
>



-- 
Atte:
Matías Aereal Aeón

**Comment by mattaereal** [comment]
Fixed in next commit. Issue name is wrong also, evilgrade's functionality is not infuenced by the warning and could run properly with it.

Thanks for the feedback!
