### ISSUE TITLE
startup error evilgrade

### ISSUE THREAD

**Issue by irbisrus** [infobyte/evilgrade#14]
Hi
After upgrade kali 
Start
evilgrade 
Can't locate isrcore/Shell.pm in @INC (you may need to install the isrcore::Shell module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./evilgrade line 25.
BEGIN failed--compilation aborted at ./evilgrade line 25.

Thank you all for the help

**Comment by d4rkn0** [comment]
i have the same problem .. can u put the solution plz

**Comment by irbisrus** [comment]
He came out of the situation by adding the lib path
"Use lib '/ usr / share / isr-evilgrade /';" in file: evilgrade
since the span refused to put the lib
