### ISSUE TITLE
how to install evilgrade 

### ISSUE THREAD

**Issue by Ahmedabdsalam** [infobyte/evilgrade#17]
when i try run evilgrade >>>>./evilgrade 
Can't locate RPC/XML.pm in @INC (you may need to install the RPC::XML module) (@INC contains: /root/evilgrade /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.2 /usr/local/share/perl/5.22.2 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at isrcore/shellz.pm line 36.
Compilation failed in require at ./evilgrade line 26.
BEGIN failed--compilation aborted at ./evilgrade line 26.

**Comment by f-amato** [comment]
Hi @Ahmedabdsalam 
You have to install it using cpan:
# cpan
# cpan> install RPC::XML

Check it out every module and installing using the same way:
    Data::Dump
    Digest::MD5
    Time::HiRes
    RPC::XML

**Comment by jkanchelov** [comment]
Maybe it will be if there are some installation instructions in the README.md so others won't stumble on such problems.

**Comment by f-amato** [comment]
Thanks @jkanchelov we are going to do it
Best

**Comment by xo0Xo0xo** [comment]
tar -xvf isr-evilgrade-2.0.0.tar.gz
mkdir: invalid option -- 'x'

what I do wrong

**Comment by f-amato** [comment]
tar zxvf

**Comment by gauravrajput1** [comment]
I install all module as you mentioned..but still getting that issue:

Failed test RPC::XML::Server::url method (set)
at t/40 server.t line 188.

'http://[:1]:38891/
doesn't match (:http:l127[.]e.Gel.]1 localhost|ip6-localhost ip6-loopback localhost.]loca
Not an ARRAY reference at t/40 server.t line 333.
Looks like your test exited with 255 just after 43.
