### ISSUE TITLE
DAP Not working

### ISSUE THREAD

**Issue by japerryy** [infobyte/evilgrade#20]
I run the DAP module and it does not show an update on my target machine. The virtual host is set at "update.speedbit.com, but after examining the MITMF results when I am DNS spoofing, I notice that it is looking for a "stub.speedbit.com". Does the virtual host need to be changed to "stub.speedbit.com? If so, how do I do that? Thank you

**Comment by f-amato** [comment]
It is possible that something change in the update process. It's been a while since we create that module. Did you try to change the vhost?

**Comment by japerryy** [comment]
Sorry, I am not too tech-savy, how do I change the vhost? 

Thanks and sorry for the late reply.

Also thanks for making a cool program.

**Comment by f-amato** [comment]
Thanks! I'm happy that you like it.
You have to change line 34 from modules/dap.pm  'update.speedbit.com' with new vhost (stub.speedbit.com) and try again
    'vh'          => '(update.speedbit.com)',
