### ISSUE TITLE
error when i try to run

### ISSUE THREAD

**Issue by Siriusblack91** [infobyte/evilgrade#22]
when i try run evilgrade >>>>./evilgrade
Can't locate isrcore/Shell.pm in @INC (you may need to install the isrcore::Shell module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./evilgrade line 25.
BEGIN failed--compilation aborted at ./evilgrade line 25.
i have already install all module by cpan. i try to install the required module isrcore::shell but there is new error: 
install isrcore::Shell
Caught SIGINT, trying to continue
Warning: Cannot install isrcore::Shell, don't know what it is.
Try the command

    i /isrcore::Shell/

to find objects with matching identifiers.

someone can help me?

**Comment by f-amato** [comment]
Hi, 
What distribution are you using?
Check if this thread help you out:
https://github.com/infobyte/evilgrade/issues/16

Best

**Comment by bcoles** [comment]
As per https://github.com/infobyte/evilgrade/issues/16#issuecomment-263376731 :

```diff
diff --git a/evilgrade b/evilgrade
index 533d5cc..1c29ce6 100755
--- a/evilgrade
+++ b/evilgrade
@@ -22,6 +22,8 @@
 # '''
 ##
 
+use FindBin;
+use lib $FindBin::Bin;
 use isrcore::Shell;
 use isrcore::shellz;
 ```
