### ISSUE TITLE
Notepad++ problem 

### ISSUE THREAD

**Issue by damianeyo** [infobyte/evilgrade#25]
failed to connect to notepad-plus-plus.org port 443: Timed out - im using ettercap, and nc, can someone help me with it please?

**Comment by f-amato** [comment]
Maybe it's not more vulnerable, keep in mind that modules works until the vendor update their update system

**Comment by ChillVibesMushroom** [comment]
So notepadplus isn’t vulnerable anymore? Because I actually visit the my ipv4:80 on my target laptop and get a bunch of information on my terminal running evilgrade
