### ISSUE TITLE
can any one help me

### ISSUE THREAD

**Issue by kurd2019** [infobyte/evilgrade#29]
whene i write ./evilgrade 
it shows to me this message

Can't locate RPC/XML.pm in @INC (you may need to install the RPC::XML module) (@INC contains: /root/eeee/evilgrade-master /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /etc/perl/isrcore/shellz.pm line 36.
Compilation failed in require at ./evilgrade line 26.
BEGIN failed--compilation aborted at ./evilgrade line 26.

**Comment by bcoles** [comment]
Try `sudo apt install librpc-xml-perl` or `cpan install RPC::XML` as per #24.

Then start evilgrade with the appropriate `-I` include directory.

```
perl -I "/usr/local/share/perl/5.30.0/XML/" ./evilgrade
```
