### ISSUE TITLE
updates?

### ISSUE THREAD

**Issue by theoneandonly-vector** [infobyte/evilgrade#4]
this project is extremely outdated..

**Comment by f-amato** [comment]
Hi @theoneandonly-vector , we haven't update evilgrade in a while. It's a open source project if you like you could contribute development or remove the plugins that it is not supported. I recommend send your patch to https://github.com/infobyte/evilgrade/pulls

**Comment by f-amato** [comment]
We have a new version have fun!

**Comment by theoneandonly-vector** [comment]
thx looks realy great :)
Am 06.06.2016 3:44 nachm. schrieb "Francisco Amato" <
notifications@github.com>:
