### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by ortholinux** [infobyte/evilgrade#6]
Evilgrade can do several malicious upgrades for several applications even cross platform like itunes and others, but there is nothing for Android devices, and there are two really popular applications in android world i.e playstore and whatsapp, if evilgrade could have something for such popular apps it would be really good. I also tried the skype upgrade on android skype version, even sniffed the urls it was sending requests to and redirected those to evilgrade, but still didn't work.

**Comment by mattaereal** [comment]
Hi @ortholinux, we'll be glad to add any module you like. Feel free to set a description for an HTTP/Plaintext update of an unsigned (or a possible bad signed) application and well work it out for you.
