### ISSUE TITLE
DeadUpdate (Asus)

### ISSUE THREAD

**Issue by hslatman** [infobyte/evilgrade#8]
Description on: http://teletext.zaibatsutel.net/post/145370716258/deadupdate-or-how-i-learned-to-stop-worrying-and

**Comment by f-amato** [comment]
Thanks @hslatman! We are going to add it in the next release

**Comment by mattaereal** [comment]
Added to current version.

Thanks again @hslatman and let us know if something is not working properly.

Closing ticket.
